[build]
    publish = "dist"
    command = "npm run build"
    functions = "netlify/functions"

[dev]
    command = "npm run dev"
    functions = "netlify/functions"
    port = 5173

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200